services:
  instaloader-api:
    build: .
    ports:
      - "8030:8000"
    environment:
      - DOWNLOAD_DIR=/app/downloads
    volumes:
      - ${HOST_DOWNLOAD_PATH:-./data/instaloader_downloads}:/app/downloads
